# baseURL
@baseURL = http://localhost:3000

###
# Find All Users
GET {{ baseURL }}/users?limit=10&page=1

###
# Find User By Id
GET {{ baseURL }}/users/99da9828-6165-4e4d-a03c-a572081c20c

###
# Create User
POST {{ baseURL }}/users
Content-Type: application/json

{
    "email": "chris@email.com",
	"password": "password"
}

###
# Modify User By Id
PUT {{ baseURL }}/users/0057db78-4788-4a1c-929b-460e69c69cd8
Content-Type: application/json

{
    "email": "chris@email.com",
    "password": "password"
}

###
# Delete User By Id
DELETE {{ baseURL }}/users/84c74248-1b02-429b-8282-92f4a7d07c3a
