# baseURL
@baseURL = http://localhost:3000

###
# Find All Users
GET {{ baseURL }}/users?limit=10&page=1&sort=createdAt&order=desc

###
# Find User By Id
GET {{ baseURL }}/users/d0297914-3b16-4ccf-a0e7-c71aaf4d0046

###
# Create User
POST {{ baseURL }}/users
Content-Type: application/json

{
    "email": "mizard@email.com",
    "username": "razim",
	"password": "password"
}

###
# Modify User By Id
PUT {{ baseURL }}/users/d0297914-3b16-4ccf-a0e7-c71aaf4d0046
Content-Type: application/json

{
    "email": "mizasrd@email.com",
    "username": "razimm"
}

###
# Delete User By Id
DELETE {{ baseURL }}/users/84c74248-1b02-429b-8282-92f4a7d07c3a
